# Generated by Django 3.2.9 on 2022-01-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
    ]
