# Generated by Django 3.2.9 on 2022-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
