# Generated by Django 3.2.9 on 2022-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_orders_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Not Approved', max_length=50),
        ),
    ]
